/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xfgryujk_longexposurecamera_CameraPreview_PictureBlender */

#ifndef _Included_com_xfgryujk_longexposurecamera_CameraPreview_PictureBlender
#define _Included_com_xfgryujk_longexposurecamera_CameraPreview_PictureBlender
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
